name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4   # ✅ latest checkout

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3   # ✅ NEW version, no v2 or v1
        with:
          path: .   # make sure index.html is at repo root

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4   # ✅ latest deploy action





